# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Optional blog
email: lakeofsoft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  will code for food
baseurl: "/thyblog" # the subpath of your site, e.g. /blog
url: "http://lakeofsoft.github.io/" # the base hostname & protocol for your site
twitter_username: lakeofsoft
github_username:  lakeofsoft

# Build settings
markdown: kramdown

highlighter: rouge
